language: node_js
node_js:
  - 0.8
addons:
  chrome: stable
before_install:
- export CHROME_BIN=chromium-browser
— export DISPLAY=:99.0
— sh -e /etc/init.d/xvfb start
- sleep 3
script:
- ./node_modules/.bin/karma start --browsers Firefox --single-run
- npm run lint
