language: node_js
node_js:
- stable
addons:
  chrome: stable
before_install:
- export CHROME_BIN=chromium-browser
— export DISPLAY=:99.0
— sh -e /etc/init.d/xvfb start
- sleep 3
script:
- npm run test
- npm run lint
